#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

- name: Format and mount disks for Pulsar/BookKeeper hosts
  hosts: broker
  connection: ssh
  become: true
  tasks:
    - name: Format disks
      filesystem:
        fstype: xfs
        dev: '{{ item }}'
      with_items:
        - '/dev/sdc'
        - '/dev/sdd'
    - name: Mount disks
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: xfs
        opts: defaults,noatime,nodiscard
        state: mounted
      with_items:
        - { path: "/mnt/data-1", src: "/dev/sdc" }
        - { path: "/mnt/data-2", src: "/dev/sdd" }

- name: Pulsar downloads
  hosts: all
  connection: ssh
  become: true
  tasks:
    - set_fact:
        zookeeperServers: "{{ groups['zookeeper'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
        private_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        serviceUrl: "pulsar://{{ hostvars[groups['broker'][0]].ansible_default_ipv4.address }}:6650/"
        httpUrl: "http://{{ hostvars[groups['broker'][0]].ansible_default_ipv4.address }}:8080/"
        pulsarDownloadUrl: "https://github.com/streamnative/pulsar/releases/download/v2.8.0-rc-202102252222/apache-pulsar-2.8.0-rc-202102252222-bin.tar.gz"
        kopDownloadUrl: "https://github.com/streamnative/kop/releases/download/v2.8.0-rc-202102261859/pulsar-protocol-handler-kafka-2.8.0-rc-202102261859.nar"
    - file: path=/opt/pulsar state=absent
    - file: path=/opt/pulsar state=directory
    - name: Download Pulsar binary package
      unarchive:
        src: "{{ pulsarDownloadUrl }}"
        remote_src: yes
        dest: /opt/pulsar
        extra_opts: ["--strip-components=1"]
    - name: Download extra metrics provider for ZooKeeper
      get_url:
        url: "https://repo.maven.apache.org/maven2/org/apache/zookeeper/zookeeper-prometheus-metrics/3.6.2/zookeeper-prometheus-metrics-3.6.2.jar"
        dest: /opt/pulsar/lib
      when: inventory_hostname in groups['zookeeper']
    - name: Create directory for protocol handlers
      file:
        path: /opt/pulsar/protocols
        state: directory
      when: inventory_hostname in groups['broker']
    - name: Download KoP package
      get_url:
        url: "{{ kopDownloadUrl }}"
        dest: /opt/pulsar/protocols
      when: inventory_hostname in groups['broker']
    - set_fact:
        private_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        max_heap_memory: "8g"
        max_direct_memory: "16g"
    - template:
        src: "pulsar/templates/pulsar_env.sh"
        dest: "/opt/pulsar/conf/pulsar_env.sh"
    - template:
        src: "pulsar/templates/bkenv.sh"
        dest: "/opt/pulsar/conf/bkenv.sh"
    - name: Change locale to en_US.utf-8
      shell: |
        echo 'LANG=en_US.utf-8
        LC_ALL=en_US.utf-8' >> /etc/environment

- name: ZooKeeper setup
  hosts: zookeeper
  connection: ssh
  become: true
  tasks:
    - set_fact:
        zid: "{{ groups['zookeeper'].index(inventory_hostname) }}"
        max_heap_memory: "512m"
        max_direct_memory: "512m"
        private_ip: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
    - file:
        path: "/opt/pulsar/{{ item }}"
        state: directory
      with_items:
        - data/zookeeper
    - template:
        src: "pulsar/templates/pulsar_env.sh"
        dest: "/opt/pulsar/conf/pulsar_env.sh"
    - template:
        src: "pulsar/templates/bkenv.sh"
        dest: "/opt/pulsar/conf/bkenv.sh"
    - template:
        src: "pulsar/templates/zoo.cfg"
        dest: "/opt/pulsar/conf/zookeeper.conf"
    - template:
        src: "pulsar/templates/myid"
        dest: "/opt/pulsar/data/zookeeper/myid"
    - template:
        src: "pulsar/templates/zookeeper.service"
        dest: "/etc/systemd/system/zookeeper.service"
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "zookeeper"
    - command: >
        bin/pulsar initialize-cluster-metadata --cluster local
        --zookeeper localhost:2181
        --configuration-store localhost:2181
        --web-service-url {{ httpUrl }}
        --broker-service-url {{ serviceUrl }}
      args:
        chdir: /opt/pulsar
      when: groups['zookeeper'][0] == inventory_hostname

- name: BookKeeper setup
  hosts: broker
  connection: ssh
  become: true
  tasks:
    - template:
        src: "pulsar/templates/bookkeeper.conf"
        dest: "/opt/pulsar/conf/bookkeeper.conf"
    - name: Install bookkeeper systemd service
      template:
        src: "pulsar/templates/bookkeeper.service"
        dest: "/etc/systemd/system/bookkeeper.service"
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "bookkeeper"

- name: Pulsar broker setup
  hosts: broker
  connection: ssh
  become: true
  tasks:
    - name: Set up broker
      template:
        src: "pulsar/templates/broker.conf"
        dest: "/opt/pulsar/conf/broker.conf"
    - template:
        src: "pulsar/templates/pulsar.service"
        dest: "/etc/systemd/system/pulsar.service"
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "pulsar"

- name: Pulsar benchmarking client setup
  hosts: client
  connection: ssh
  become: true
  tasks:
    - name: Set up client config
      template:
        src: "pulsar/templates/client.conf"
        dest: "/opt/pulsar/conf/client.conf"
    - file: path=/opt/benchmark state=absent
    - name: Copy benchmark code
      unarchive:
        src: ../package/target/openmessaging-benchmark-0.0.1-SNAPSHOT-bin.tar.gz
        dest: /opt
    - shell: mv /opt/openmessaging-benchmark-0.0.1-SNAPSHOT /opt/benchmark
    - template:
        src: "pulsar/templates/workers.yaml"
        dest: "/opt/benchmark/workers.yaml"
    - name: Get list of driver config files
      raw: ls -1 /opt/benchmark/driver-pulsar/*.yaml
      register: drivers_list
    - name: Configure service URL
      lineinfile:
        dest: '{{ item }}'
        regexp: '^  serviceUrl\: '
        line: '  serviceUrl: {{ serviceUrl }}'
      with_items: '{{ drivers_list.stdout_lines }}'
    - name: Configure http URL
      lineinfile:
        dest: '{{ item }}'
        regexp: '^  httpUrl: '
        line: '  httpUrl: {{ httpUrl }}'
      with_items: '{{ drivers_list.stdout_lines }}'
    - name: Configure memory
      lineinfile:
         dest: /opt/benchmark/bin/benchmark-worker
         regexp: '^JVM_MEM='
         line: 'JVM_MEM="-Xms8G -Xmx8G -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+PerfDisableSharedMem -XX:+AlwaysPreTouch -XX:-UseBiasedLocking"'
    - name: Install benchmark systemd service
      template:
        src: "pulsar/templates/benchmark-worker.service"
        dest: "/etc/systemd/system/benchmark-worker.service"
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "benchmark-worker"

- name: Prometheus setup
  hosts: prometheus
  connection: ssh
  become: true
  tasks:
    - name: Install docker
      apt:
        name: docker.io
    - file:
        path: "/opt/prometheus/{{ item }}"
        state: directory
      with_items:
        - data
    - template:
        src: "pulsar/templates/prometheus.service"
        dest: "/etc/systemd/system/prometheus.service"
    - template:
        src: "pulsar/templates/pulsar-dashboard.service"
        dest: "/etc/systemd/system/pulsar-dashboard.service"
    - template:
        src: "pulsar/templates/prometheus.yml"
        dest: "/opt/prometheus/prometheus.yml"
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "prometheus"
    - systemd:
        state: restarted
        daemon_reload: yes
        name: "pulsar-dashboard"
