#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

- name: Pulsar downloads
  hosts: broker:zookeeper
  connection: ssh
  become: true
  tasks:
    - set_fact:
        zookeeperServers: "{{ groups['zookeeper'] | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
        serviceUrl: "pulsar://{{ hostvars[groups['broker'][0]].private_ip }}:6650/"
        httpUrl: "http://{{ hostvars[groups['broker'][0]].private_ip }}:8080/"
        pulsarDownloadUrl: "https://github.com/streamnative/pulsar/releases/download/v2.8.0-rc-202102252222/apache-pulsar-2.8.0-rc-202102252222-bin.tar.gz"
        kopDownloadUrl: "https://github.com/streamnative/kop/releases/download/v2.8.0-rc-202102261859/pulsar-protocol-handler-kafka-2.8.0-rc-202102261859.nar"
    - file: path=/opt/pulsar state=absent
    - file: path=/opt/pulsar state=directory
    - name: Download Pulsar binary package
      unarchive:
        src: "{{ pulsarDownloadUrl }}"
        remote_src: yes
        dest: /opt/pulsar
        extra_opts: ["--strip-components=1"]
    - name: Create directory for protocol handlers
      file:
        path: /opt/pulsar/protocols
        state: directory
      when: inventory_hostname in groups['broker']
    - name: Download KoP package
      get_url:
        url: "{{ kopDownloadUrl }}"
        dest: /opt/pulsar/protocols
      when: inventory_hostname in groups['broker']
    - set_fact:
        private_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        max_heap_memory: "8g"
        max_direct_memory: "16g"
    - template:
        src: "pulsar/templates/pulsar_env.sh"
        dest: "/opt/pulsar/conf/pulsar_env.sh"
    - template:
        src: "pulsar/templates/bkenv.sh"
        dest: "/opt/pulsar/conf/bkenv.sh"
    - name: Change locale to en_US.utf-8
      shell: |
        echo 'LANG=en_US.utf-8
        LC_ALL=en_US.utf-8' >> /etc/environment
