#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

- name: Prometheus installation
  hosts: prometheus
  connection: ssh
  become: true
  tasks:
    - set_fact:
        prometheusVersion: "2.21.0"
    - file: path=/opt/prometheus state=directory
    - name: Download Prometheus Binary Package
      unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheusVersion }}/prometheus-{{ prometheusVersion }}.linux-amd64.tar.gz
        remote_src: yes
        dest: /opt/prometheus
        extra_opts: ["--strip-components=1"]

- name: Prometheus setup
  hosts: prometheus
  connection: ssh
  become: true
  tasks:
    - name: Install docker
      apt:
        name: docker.io
    - file: path=/opt/prometheus/data state=directory
    - template:
        src: templates/prometheus.service
        dest: /etc/systemd/system/prometheus.service
    - template:
        src: templates/pulsar-dashboard.service
        dest: /etc/systemd/system/pulsar-dashboard.service
    - template:
        src: templates/prometheus.yml
        dest: /opt/prometheus/prometheus.yml
    - systemd:
        state: restarted
        daemon_reload: yes
        name: prometheus
    - systemd:
        state: restarted
        daemon_reload: yes
        name: pulsar-dashboard
